config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root "groups#index", as: :authenticated_root
    resources :groups do
      resources :purchases
    end
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    can :manage, Purchase, author_id: user.id
    can :manage, Group, user_id: user.id
    can :manage, User, id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :purchases, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
  validates :user_id, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases, foreign_key: 'author_id'
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show]

  def index
    @groups = current_user.groups
  end

  def show; end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to group_url(@group), notice: 'Group was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def show
    @group = Group.find(params[:group_id])
    @purchase = @group.purchases.find_by(id: params[:id])

    return unless @purchase.nil?

    redirect_to group_path, alert: 'Purchase does not exist.'
  end

  def new
    @group = Group.find(params[:group_id])
    @purchase = @group.purchases.build
  end

  def create
    @group = Group.find(params[:group_id])
    @purchase = @group.purchases.build(purchase_params)
    @purchase.author = current_user

    if @purchase.save
      redirect_to group_path(@group), notice: 'Purchase was successfully created.'
    else
      render :new
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "max-w-sm mx-auto") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-5">
    <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="mb-5">
    <%= form.label :icon, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.select :icon, options_for_select([
      ['Star', 'M12 17.75l-6.172 3.245 1.179-6.873-4.993-4.867 6.9-1.002L12 2l3.086 6.253 6.9 1.002-4.993 4.867 1.179 6.873z'],
      ['Bell', 'M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9" />  <path d="M13.73 21a2 2 0 0 1-3.46 0'],
      ['Heart', 'M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z'],
      ['Bulb', 'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z'],
      ['House', 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6'],
      ['Key', 'M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z'],
      ['Briefcase', 'M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z'],
      ['Envelop', 'M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z']
    ]), {}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="flex space-between mb-5 mt-10 gap-20">
    <%= form.submit class: "text-white bg-[#5fb523] hover:bg-[#3778c2] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>

     <%= link_to "Back to Groups", groups_path, class: "text-white bg-[#5fb523] hover:bg-[#3778c2] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center ml-6" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="w-full bg-[#3778c2] items-center max-w-screen-xlmx-auto p-5 gap-20">
  <h2 class="text-2xl bg-[#3778c2] text-white text-center">Groups</h2>
</div>

<div class="flex flex-col justify-between">
  <% @groups.each do |group| %>
    <%= link_to group_path(group) do %>
      <div class="flex p-8 justify-between m-3 bg-white">
        <svg class="h-8 w-8 text-blue-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="<%= group.icon %>"/></svg>
        <h3 class="text-2xl font-bold"><%= group.name %></h3>
        <h3 class="text-xl font-bold"><%= number_with_precision(group.purchases.sum(:amount), precision: 2) %> €</h3>
      </div>
    <% end %>
  <% end %>

  <%= link_to "New group", new_group_path, class: "text-white bg-[#5fb523] hover:bg-[#3778c2] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium text-xl w-full py-10 text-center fixed bottom-0 left-0" %>
</div>

app/views/groups/new.html.erb
<div class="max-w-sm mx-auto">
  <h2 class="font-bold text-4xl my-10">New Group</h2>

  <%= render "form", group: @group %>
</div>

app/views/groups/show.html.erb
<div class="w-full bg-[#3778c2] items-center max-w-screen-xlmx-auto p-5 gap-20 flex">
  <%= link_to "<", groups_path, class: "text-white text-2xl bg-[#3778c2] font-medium sm:w-auto px-5 py-2.5 text-center" %>
  <h2 class="text-2xl bg-[#3778c2] text-white text-center ml-4"><%= @group.name %></h2>
</div>

<div>
  <div>
    <h2 class="text-2xl bg-[#3778c2] text-white text-center py-3">Total Purchases: <%=number_with_precision(@group.purchases.sum(:amount), precision: 2) %> €</h2>

    <% @group.purchases.order(created_at: :desc).each do |purchase| %>
      <div class="flex flex-col gap-2 text-xl p-8 justify-between bg-white m-3">
        <h3 class="font-bold"><%= purchase.name %></h3>
        <p>Amount: <%= number_with_precision(purchase.amount, precision: 2) %> €</p>
        <p>Date: <%= purchase.created_at.to_date %></p>
      </div>
    <% end %>
  </div>

  <%= link_to "New Purchase", new_group_purchase_path(@group), class: "text-white bg-[#5fb523] hover:bg-[#3778c2] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium text-xl w-full py-10 text-center fixed bottom-0 left-0" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Purse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#F1F1F1]">
    <main class="container mx-auto flex flex-col">
      <nav class="bg-[#3778c2] text-white">
        <ul class="flex gap-2 px-10 py-3 items-center">
          <h1 class="font-bold text-xl mr-5">Rails Purse</h1>
          <li class="mr-2"><%= link_to "Home", root_path%></li>
          <% if user_signed_in? %>
            <li class="mr-2"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="mr-2"><%= link_to "Log in", new_user_session_path %></li>
            <li class="mr-2"><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>

      <% if alert %>
        <p class="text-red-400 text-center font-bold"><%= alert %></p>
      <% end %>
      <% if notice %>
        <p class="text-green-400 text-center font-bold"><%= notice %></p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: [@group, @purchase], local: true, class: "max-w-sm mx-auto") do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-5">
    <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="mb-5">
    <%= form.label :amount, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.number_field :amount, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="flex items-start mb-5 gap-20">
    <%= form.submit class: "text-white bg-[#5fb523] hover:bg-[#3778c2] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>

    <%= link_to "Back to Purchases", group_path(@group), class: "text-white bg-[#5fb523] hover:bg-[#3778c2] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center ml-10" %>
  </div>
<% end %>

app/views/purchases/new.html.erb
<div class="max-w-sm mx-auto">
  <h2 class="font-bold text-4xl my-10">New Purchase</h2>

  <%= render "form", purchase: @purchase %>
</div>